### ISSUE TITLE
Change default block tag name

### ISSUE THREAD

**Issue by friendOfOurs** [alexkrolick/react-quill#4]
Hi,

Is there a way to change default block tag name? Smth. like in pure Quill:

```
var Block = Quill.import('blots/block');
Block.tagName = 'LI';
Quill.register(Block, true);
```

Best

**Comment by alexkrolick** [comment]
Currently only the modules config is exposed, so this sounds tricky with the current wrapper. I'd suggest filing this on the original repo, maybe someone there has an idea.
