### ISSUE TITLE
defaultValue not updating on setState

### ISSUE THREAD

**Issue by Gorb** [alexkrolick/react-quill#5]
Using version 2.0.2, React version 15.3.2. I'm setting `defaultValue` to a state-based value. This works when the `ReactQuill` component is made visible for the first time.

However, this does not work if the component is already visible and I update the state. The old `defaultValue` is still shown. This will only update if I set the new state, render the `ReactQuill` component invisible, and then make it visible again.

I've logged the value during this time, and it consoles out as the updated state value. Other instances of this value being displayed update as expected; only the `defaultValue` of `ReactQuill` doesn't. `forceUpdate` doesn't resolve this (not that I'd expect it to as `setState` is recalling `render` as I'd expect it to, just covering what I've tried).

**Comment by alexkrolick** [comment]
Right, it's only set when the component mounts. After that you would want to set `value`.

**Comment by Gorb** [comment]
Hah, thanks, that works. The last time I tried that it wasn't working properly, must've been something to do with my edit states.
